### ISSUE TITLE
Middleware and context

### ISSUE THREAD

**Issue by yozik04** [senacor/azure-function-middleware#428]
How would you access `userId` inside `handler` function?

https://github.com/senacor/azure-function-middleware/blob/ac1586b0a72aa6325358f0cf4eb9b50dbf50e729/example/src/test-jwt-authorization-function.ts#L6-L9

**Comment by ziegler-daniel** [comment]
Hi @yozik04,

you can access the parsed JWT claims in the handler via `context.extraInputs.get('jwt')`. I have extended the example [test-jwt-authorization-function.ts](https://github.com/senacor/azure-function-middleware/blob/master/example/src/test-jwt-authorization-function.ts) accordingly.

I hope this helps you.
